backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/uploads
public_folder: uploads
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Headline", name: "headline", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Category"
        name: "category"
        widget: "select" 
        options:
          - {label: "Exclusive", value: "exclusive"}
          - {label: "News", value: "news"}
          - {label: "Politics", value: "politics"}
          - {label: "Opinion", value: "opinion"}
          - {label: "Interviews", value: "interviews"}
          - {label: "Culture", value: "culture"}
      - {label: "Top Story", name: "topstory", widget: "boolean", default: false}
      - {label: "Featured Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      
      
          